/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jtext_curses_CursesImpl */

#ifndef _Included_org_jtext_curses_CursesImpl
#define _Included_org_jtext_curses_CursesImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesImpl_init
  (JNIEnv *, jobject);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    getScreenWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jtext_curses_CursesImpl_getScreenWidth
  (JNIEnv *, jobject);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    getScreenHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jtext_curses_CursesImpl_getScreenHeight
  (JNIEnv *, jobject);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    setColor
 * Signature: (Lorg/jtext/curses/CharacterColor;Lorg/jtext/curses/CharacterColor;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesImpl_setColor
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    setAttributes
 * Signature: (Ljava/util/EnumSet;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesImpl_setAttributes
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    drawHorizontalLineAt
 * Signature: (Lorg/jtext/curses/Point;CI)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesImpl_drawHorizontalLineAt
  (JNIEnv *, jobject, jobject, jchar, jint);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    drawVerticalLineAt
 * Signature: (Lorg/jtext/curses/Point;CI)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesImpl_drawVerticalLineAt
  (JNIEnv *, jobject, jobject, jchar, jint);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    printStringAt
 * Signature: (Lorg/jtext/curses/Point;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesImpl_printStringAt
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    putCharAt
 * Signature: (Lorg/jtext/curses/Point;C)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesImpl_putCharAt
  (JNIEnv *, jobject, jobject, jchar);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    moveCursor
 * Signature: (Lorg/jtext/curses/Point;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesImpl_moveCursor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    drawVerticalLine
 * Signature: (CI)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesImpl_drawVerticalLine
  (JNIEnv *, jobject, jchar, jint);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    drawHorizontalLine
 * Signature: (CI)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesImpl_drawHorizontalLine
  (JNIEnv *, jobject, jchar, jint);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    printString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesImpl_printString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    printChar
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesImpl_printChar
  (JNIEnv *, jobject, jchar);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesImpl_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    getCh
 * Signature: ()Lorg/jtext/curses/ReadKey;
 */
JNIEXPORT jobject JNICALL Java_org_jtext_curses_CursesImpl_getCh
  (JNIEnv *, jobject);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    refresh
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesImpl_refresh
  (JNIEnv *, jobject);

/*
 * Class:     org_jtext_curses_CursesImpl
 * Method:    clearScreen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesImpl_clearScreen
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
