/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jtext_curses_CursesDriver */

#ifndef _Included_org_jtext_curses_CursesDriver
#define _Included_org_jtext_curses_CursesDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_init
  (JNIEnv *, jobject);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    getScreenWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jtext_curses_CursesDriver_getScreenWidth
  (JNIEnv *, jobject);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    getScreenHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jtext_curses_CursesDriver_getScreenHeight
  (JNIEnv *, jobject);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    createWindow
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_jtext_curses_CursesDriver_createWindow
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    setColor
 * Signature: (ILorg/jtext/curses/CharacterColor;Lorg/jtext/curses/CharacterColor;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_setColor
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    setBackgroundColor
 * Signature: (ILorg/jtext/curses/CharacterColor;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_setBackgroundColor
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    setForegroundColor
 * Signature: (ILorg/jtext/curses/CharacterColor;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_setForegroundColor
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    onAttributes
 * Signature: (I[Lorg/jtext/curses/CharacterAttribute;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_onAttributes
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    onAttribute
 * Signature: (ILorg/jtext/curses/CharacterAttribute;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_onAttribute
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    offAttribute
 * Signature: (ILorg/jtext/curses/CharacterAttribute;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_offAttribute
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    drawHorizontalLineAt
 * Signature: (IIICI)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_drawHorizontalLineAt
  (JNIEnv *, jobject, jint, jint, jint, jchar, jint);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    drawVerticalLineAt
 * Signature: (IIICI)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_drawVerticalLineAt
  (JNIEnv *, jobject, jint, jint, jint, jchar, jint);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    printStringAt
 * Signature: (IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_printStringAt
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    putCharAt
 * Signature: (IIIC)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_putCharAt
  (JNIEnv *, jobject, jint, jint, jint, jchar);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    changeAttributeAt
 * Signature: (IIIILorg/jtext/curses/CharacterColor;Lorg/jtext/curses/CharacterColor;[Lorg/jtext/curses/CharacterAttribute;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_changeAttributeAt
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject, jobject, jobjectArray);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    moveCursor
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_moveCursor
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    drawVerticalLine
 * Signature: (ICI)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_drawVerticalLine
  (JNIEnv *, jobject, jint, jchar, jint);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    drawHorizontalLine
 * Signature: (ICI)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_drawHorizontalLine
  (JNIEnv *, jobject, jint, jchar, jint);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    printString
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_printString
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    putChar
 * Signature: (IC)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_putChar
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    changeAttribute
 * Signature: (I[Lorg/jtext/curses/CharacterAttribute;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_changeAttribute
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    bell
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_bell
  (JNIEnv *, jobject);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    getCh
 * Signature: ()Lorg/jtext/curses/ReadKey;
 */
JNIEXPORT jobject JNICALL Java_org_jtext_curses_CursesDriver_getCh
  (JNIEnv *, jobject);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    refresh
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_refresh
  (JNIEnv *, jobject, jint);


/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    doUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_doUpdate
  (JNIEnv *, jobject);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    clearScreen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_clearScreen
  (JNIEnv *, jobject);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    clear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_clear
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    clearStyle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_clearStyle
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    getCursorX
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jtext_curses_CursesDriver_getCursorX
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    getCursorY
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jtext_curses_CursesDriver_getCursorY
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    moveWindow
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jtext_curses_CursesDriver_moveWindow
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    resizeWindow
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jtext_curses_CursesDriver_resizeWindow
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    deleteWindow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_deleteWindow
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    setBackground
 * Signature: (ILorg/jtext/curses/CellDescriptor;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_setBackground
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    changeBackground
 * Signature: (ILorg/jtext/curses/CellDescriptor;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_changeBackground
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    drawBox
 * Signature: (ILorg/jtext/curses/CellDescriptor;Lorg/jtext/curses/CellDescriptor;Lorg/jtext/curses/CellDescriptor;Lorg/jtext/curses/CellDescriptor;Lorg/jtext/curses/CellDescriptor;Lorg/jtext/curses/CellDescriptor;Lorg/jtext/curses/CellDescriptor;Lorg/jtext/curses/CellDescriptor;)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_drawBox__ILorg_jtext_curses_CellDescriptor_2Lorg_jtext_curses_CellDescriptor_2Lorg_jtext_curses_CellDescriptor_2Lorg_jtext_curses_CellDescriptor_2Lorg_jtext_curses_CellDescriptor_2Lorg_jtext_curses_CellDescriptor_2Lorg_jtext_curses_CellDescriptor_2Lorg_jtext_curses_CellDescriptor_2
  (JNIEnv *, jobject, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     org_jtext_curses_CursesDriver
 * Method:    drawBox
 * Signature: (ICCCCCCCC)V
 */
JNIEXPORT void JNICALL Java_org_jtext_curses_CursesDriver_drawBox__ICCCCCCCC
  (JNIEnv *, jobject, jint, jchar, jchar, jchar, jchar, jchar, jchar, jchar, jchar);

#ifdef __cplusplus
}
#endif
#endif
